name: train_credit_defaults_model
display_name: Train Credit Defaults Model
# version: 1 # Not specifying a version will automatically update the version
type: command
inputs:
  train_data: 
    type: uri_folder
  test_data: 
    type: uri_folder
  n_estimators:
    type: number     
  registered_model_name:
    type: string
outputs:
  model_save_path:
    type: uri_folder
code: .
environment:
  # for this step, we'll use an AzureML curate environment
  azureml://registries/azureml/environments/sklearn-1.0/labels/latest
command: >-
  python training.py 
  --train_data ${{inputs.train_data}} 
  --test_data ${{inputs.test_data}} 
  --n_estimators ${{inputs.n_estimators}}
  --registered_model_name ${{inputs.registered_model_name}} 
  --model_save_path ${{outputs.model_save_path}}